-- One-time bind tokens: let an admin hand a short-lived, single-use code to
-- a verified user who has not yet set a query code, so the user can set
-- their own first query code. Only the token hash is stored — never the
-- plaintext. No tokens are generated by this migration and no existing user
-- rows are modified.

create table if not exists user_query_code_bind_tokens (
	id uuid primary key default gen_random_uuid(),
	user_id uuid not null references users(id),
	token_hash text not null,
	expires_at timestamptz not null,
	used_at timestamptz,
	failed_attempts integer not null default 0,
	created_by_admin_id uuid not null references admins(id),
	created_at timestamptz not null default now(),
	invalidated_at timestamptz
);

create index if not exists idx_bind_tokens_user_id on user_query_code_bind_tokens(user_id);
create index if not exists idx_bind_tokens_expires_at on user_query_code_bind_tokens(expires_at);
create index if not exists idx_bind_tokens_created_by on user_query_code_bind_tokens(created_by_admin_id);
